version: '3.8'

services:
  main_database:
    image: postgres:alpine3.18
    volumes:
      - ./main_database:/var/lib/postgresql/data
    container_name: main_database
    environment:
      - POSTGRES_USER=${DEV_PG_DB_USER}
      - POSTGRES_PASSWORD=${DEV_PG_DB_PASS}
      - POSTGRES_DB=${DEV_PG_DATABASE}
    ports:
      - '${DEV_PG_DB_PORT}:5432'
    expose:
      - ${DEV_PG_DB_PORT}
    healthcheck:
      test:
        ['CMD-SHELL', 'pg_isready -U ${DEV_PG_DB_USER} -d ${DEV_PG_DATABASE}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./logs:/app/logs
      - /app/node_modules
    ports:
      - '5000:5000'
    restart: always
    depends_on:
      - main_database